# Generated by Django 2.2.5 on 2019-09-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190911_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='SongModel',
        ),
    ]
